# Generated by Django 2.2 on 2020-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('found', 'Foundation'), ('non_gov_org', 'Non governmental organization'), ('loc_org', 'Local collection')], default='found', max_length=50),
        ),
    ]
